apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  storageClassName: standard
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mysql       # Local path inside Minikube VM
  persistentVolumeReclaimPolicy: Retain