apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
 
  mysql-user: dXNlcg==        # "user" in base64
  mysql-password: cGFzc3dvcmQ=  # "password" in base64
  mysql-database: bXlkYg==      # "mydb" in base64
